language: objective-c
osx_image: xcode6.4

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
    - set -o pipefail
    - xcodebuild -workspace AeroGearHttp.xcworkspace -scheme AeroGearHttp -sdk iphonesimulator -destination "OS=7.1,name=iPhone 4S" -configuration clean test
    - xcodebuild -workspace AeroGearHttp.xcworkspace -scheme AeroGearHttp -sdk iphonesimulator -destination "OS=8.4,name=iPhone 6 Plus" -configuration clean test


